export default {
  SPLASH: "Splash",
  LOGIN: "Login",
  REGISTER: "Register",
  HOME: "Home",
  EXPENSE: "Expense",
  PROFILE: "Profile",
  SETTINGS: "Settings",
  ABOUT: "About",
  ADD_EXPENSE: "AddExpense",
  EDIT_EXPENSE: "EditExpense",
  CHANGE_PASSWORD: "ChangePassword",
  FORGOT_PASSWORD: "ForgotPassword",
  EDIT_PROFILE: "EditProfile",
};